#!/bin/sh

echo This script installs and configures a minimaly riced and highly configurable dwm system with dmenu and suckless terminal
echo do you wish to continue? [y/n]
read answer
if [ "$answer" = "y" -o "$answer" = "Y" -o "$answer" = "yes" -o "$answer" = "Yes" ]; then
    echo setting up dwm, dmenu and st...
    mkdir ~/.local/src
    cd ~/.local/src
    git clone https://github.com/bugswriter/dmenu
    git clone https://github.com/bugswriter/dwm
    git clone https://github.com/bugswriter/st
    sudo pacman -S --needed libxft
    sudo pacman -S --needed libxinerama
    cd ~/.local/src/dmenu
    make clean install
    cd ~/.local/src/dwm
    make clean install
    cd ~/.local/src/st
    make clean install
    cd ~
    cp /etc/X11/xinitrc ~/.xinitrc
   
# Update .xinitrc to exec dwm on startx
    file="$HOME/.xinitrc"
    total_lines=$(wc -l < "$file")
    start_line=$((total_lines - 5))
    sed -i "${start_line},\$d; \$aexec dwm" "$file"

elif [ "$answer" = "n" -o "$answer" = "N" -o "$answer" = "no" -o "$answer" = "No" ]; then 
    echo "(1) abort rice process"
    echo "(2) continue to resolution managment"
    echo "1 or 2"
    read choice
    if [ "$choice" = "1" ]; then
        echo aborting script...
        exit 0
    elif [ "$choice" = "2" ]; then
        continue
    fi
fi

startx
echo establishing resolution...
sudo pacman -S --needed xorg-xrandr


while true
do  echo finding current resolution settings...
    xrandr 
    echo please enter the name of your monitor or screen i.e. Virtual1'\n'
    read monitor_name
    echo please enter your desired resolution i.e. 1920x1080
    read resolution
    xrandr --output $monitor_name --mode $resolution
    echo would you like to make changes to the resolution? [y/n]
    read answer 
    if [ "$answer" = "n" -o "$answer" = "no" -o "$answer" = "No" -o "$answer" = "NO" ]; then
        break
    fi
done

sudo pacman -S --needed wget
echo setting up wallpaper management...
cd ~
sudo pacman -S --needed xwallpaper
mkdir wallpapers

# use default wallpaper
wget 'https://w.wallhaven.cc/full/3l/wallhaven-3lrw69.jpg' -O '~/wallpapers/windwaker.jpg'


echo installing zsh and zimfw framework...
sudo pacman -S --needed zsh
chsh -s $(which zsh)
curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
zsh
echo "PROMPT=$'\n'"%F{cyan}[%n@%f%F{magenta}%m %F{yellow}%~%f]${git_info[prompt]}%f$ "" >> ~/.zshrc
source ~/.zshrc
sudo pacman -S --needed xcompmgr
setsid xcompmgr

sudo pacman -S python-pywal
mkdir ~/.local/bin
cd ~/.local/bin
touch imagine
chmod +x imagine

sudo pacman -S xdotool
# Make script to update wallpaper and colorscheme
echo -e "#!/bin/sh
\n
\n
if [ $# -ne 1 ]; then\n
	echo "Usage: imagine <image file>"\n
	exit 1\n
fi\n
\n
background="$1"\n
\n
echo "imagining $background..."\n
\n
#clear cache\n
wal -c\n
\n
#set background\n
xwallpaper --zoom $background\n
\n
#update theme\n
wal -i $background\n
xdotool key Super+F5\n
\n
#status bar\n
dwmblocks &\n
\n
exit 0\n" >> ~/.local/bin/imagine

./imagine ~/wallpapers/windwaker.jpg

echo -e "\nexport PATH=$HOME/.local/bin:$PATH" >> ~/.zshrc

# set up .xinitrc file to run tools on start up

echo rice is complete!
echo 'simply run "imagine <wallpaperimage.jpg>" to update colorscheme and wallpaper'
exit 0












