#!/bin/sh

read -p "This script installs and configures a minimally riced and highly configurable dwm system with dmenu and suckless terminal
do you wish to continue? [y/n]" answer

# function to check if a program is installed
is_installed() {
    command -v "$1" >/dev/null 2>&1
}

if [ "$answer" = "y" ] || [ "$answer" = "Y" ] || [ "$answer" = "yes" ] || [ "$answer" = "Yes" ]; then
    echo setting up dwm, dmenu and st...

    if is_installed dmenu || is_installed dwm || is_installed st; then
        echo "build error"
        exit 1

    else
	# download and install dmenu, dwm, and st
        mkdir -p ~/.local/src
        cd ~/.local/src || exit
        git clone https://github.com/bugswriter/dmenu
        git clone https://github.com/bugswriter/dwm
        git clone https://github.com/bugswriter/st
        sudo pacman -S --needed libxft
        sudo pacman -S --needed libxinerama
        cd ~/.local/src/dmenu || exit 
        make clean install
        sleep 5
        cd ~/.local/src/dwm || exit
        make clean install 
        sleep 5
	cd ~/.local/src/st || exit
        make clean install
        sleep 5
        cd ~ || exit
        cp /etc/X11/xinit/xinitrc ~/.xinitrc
    

# Update .xinitrc to exec dwm on startx
        file="$HOME/.xinitrc"
        total_lines=$(wc -l < "$file")
        start_line=$((total_lines - 5))
        sed -i "${start_line},\$d; \$aexec dwm" "$file"
        cat ~/.xinitrc
        read -p "is execdwm at bottom" answer
        if [ "$answer" = "n" ] || [ "$answer" = "N" ] || [ "$answer" = "no" ] || [ "$answer" = "No" ]; then
            exit 1 
        fi
    fi  

elif [ "$answer" = "n" ] || [ "$answer" = "N" ] || [ "$answer" = "no" ] || [ "$answer" = "No" ]; then
    echo aborting script...
    exit 0
else 
    echo invalid input
    exit 1
fi

read -p "would you like to run startx to continue installation?" answer

if [ "$answer" = "y" ] || [ "$answer" = "Y"  ] || [ "$answer" = "yes"  ] || [ "$answer" = "Yes" ]; then
    echo run rice script on startup to finish rice. running startx...
    sleep 3
    startx
elif [ "$answer" = "n" ] || [ "$answer" = "N"  ] || [ "$answer" = "no"  ] || [ "$answer" = "No" ]; then 
    echo aborting script...
    exit 0
else 
    echo invalid input
    exit 1
fi
