#!/bin/sh

echo establishing resolution...
sudo pacman -S --needed xorg-xrandr
        
while true
do  
echo 'finding current resolution settings...'
xrandr 
    read -p 'please enter the name of your monitor or screen i.e. Virtual-1' monitor_name
    read -p 'please enter your desired resolution i.e. 1920x1080' resolution
    xrandr --output $monitor_name --mode $resolution
    read -p 'would you like to make changes to the resolution? [y/n]' answer 
    if [ "$answer" = "n" ] || [ "$answer" = "no" ] || [ "$answer" = "No" ] || [ "$answer" = "NO" ]; then
        break
    elif [ "$answer" = "y" ] || [ "$answer" = "yes" ] || [ "$answer" = "Yes" ] || [ "$answer" = "YES" ]; then
        continue
    else
        echo 'invalid input aborting script' && exit 1
    fi
done

sudo pacman -S --needed wget
echo 'Setting up wallpaper management...'
cd ~
sudo pacman -S --needed xwallpaper
mkdir wallpapers

# use default wallpaper
wget 'https://w.wallhaven.cc/full/3l/wallhaven-3lrw69.jpg' -O '~/wallpapers/windwaker.jpg'
 
echo 'installing zsh and zimfw framework...'
sleep 3
sudo pacman -S --needed zsh
chsh -s $(which zsh)
curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
sudo pacman -S --needed xcompmgr

sudo pacman -S python-pywal
cd $HOME/.local
git clone https://github.com/Steven-Alvarado/bin.git 
chmod +x $HOME/.local/bin/*
cd $HOME/.local/bin
rm -rf dwmblocks
git clone https://github.com/bugswriter/dwmblocks.git
cd dwmblocks
sudo make install
cd $HOME/.local/bin

sudo pacman -S xdotool
./imagine $HOME/wallpapers/windwaker.jpg
setsid xcompmgr &
# Export path to ~/.local/bin in zsh
echo -e '\nexport PATH=$HOME/.local/bin:$PATH' >> ~/.zshrc


# Set up .xinitrc file to run tools on start-up
sed -i '$d' $HOME/.xinitrc
echo -e "# Configure color scheme and background\nimagine ~/wallpapers/windwaker.jpg &\n\n# 
Transparency\nxcompmgr &\n\nexec dwm" >> $HOME/.xinitrc
echo 'rice is complete!'
echo "simply run 'imagine <wallpaperimage.jpg>' to update color scheme and wallpaper"
echo 'configure changes to .xinitrc and .zshrc accordingly'
exit 0
